import React from "react";
import type { Metadata } from "next";
import "./globals.css";
import { Nav } from "./components/nav";
import { Noto_Sans, Inter } from "next/font/google";

const noto = Noto_Sans({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-noto",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["500", "700"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const links = ["Home", "Contact Me"];

export default function RootLayout({
  children,
}: Readonly<{
	children: React.ReactNode;
}>) {
  const links = [
    { href: "/", label: "Home" },
    { href: "/contact-me", label: "Contact Me" }
  ];
  
  return (
    <html className={`${noto.variable} ${inter.variable}`} lang="en">
      <body>
        <Nav links={links} />
        {children}
      </body>
    </html>
  );
}
