import Footer from './Footer'
import Navbar from '../elements/Navigation'
import Contact from './Contact'
import About from './About'
import Experience from './Experience'
import Work from './Work'
import Greetings from './Greetings'
import Main from './Main'
import SideMenu from './SideMenu'
export { Navbar, SideMenu, Main, Greetings, About, Experience, Work, Contact, Footer }